services:
  server:
    container_name: cokathon
    image: marshmallowing/cokathon:latest
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
